/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const stdlib_docs: (a: number, b: number) => any;
export const __wbg_analyzer_free: (a: number, b: number) => void;
export const analyzer_allInlayHints: (a: number) => any;
export const analyzer_analyze: (a: number, b: number, c: number, d: number, e: number) => any;
export const analyzer_codeLenses: (a: number, b: number, c: number) => any;
export const analyzer_colorPresentations: (a: number, b: number, c: number, d: number, e: number) => any;
export const analyzer_completionsAt: (a: number, b: number, c: number) => any;
export const analyzer_definitionAt: (a: number, b: number, c: number) => any;
export const analyzer_diagnostics: (a: number) => any;
export const analyzer_documentColors: (a: number) => any;
export const analyzer_documentSymbols: (a: number) => any;
export const analyzer_foldingRanges: (a: number) => any;
export const analyzer_highlightsAt: (a: number, b: number, c: number) => any;
export const analyzer_hoverAt: (a: number, b: number, c: number, d: number, e: number) => any;
export const analyzer_incomingCallsFor: (a: number, b: any) => any;
export const analyzer_inlayHints: (a: number, b: number, c: number, d: number, e: number) => any;
export const analyzer_new: () => number;
export const analyzer_outgoingCallsFor: (a: number, b: any) => any;
export const analyzer_prepareCallHierarchyAt: (a: number, b: number, c: number) => any;
export const analyzer_prepareRenameAt: (a: number, b: number, c: number) => any;
export const analyzer_referencesAt: (a: number, b: number, c: number, d: number) => any;
export const analyzer_renameAt: (a: number, b: number, c: number, d: number, e: number) => any;
export const analyzer_resolveSymbolAt: (a: number, b: number, c: number) => any;
export const analyzer_semanticTokens: (a: number) => any;
export const analyzer_setLocale: (a: number, b: number, c: number) => void;
export const analyzer_signatureHelpAt: (a: number, b: number, c: number) => any;
export const analyzer_sourceFiles: (a: number) => any;
export const analyzer_typeDefinitionAt: (a: number, b: number, c: number) => any;
export const analyzer_withLocale: (a: number, b: number) => number;
export const analyzer_workspaceSymbols: (a: number, b: number, c: number) => any;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_start: () => void;
