#!/usr/bin/env bash
# Build the WASM playground engine and optimize the output.
#
# Usage: ./scripts/build-wasm.sh
#
# Prerequisites:
#   - wasm-pack: cargo install wasm-pack
#   - wasm-opt (optional): installed via binaryen package

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
WASM_OUT="$ROOT_DIR/website/wasm-pkg"

echo "==> Building WASM engine..."
wasm-pack build --target web "$ROOT_DIR/website/engine" --out-dir "$WASM_OUT"

# Remove unnecessary files generated by wasm-pack
rm -f "$WASM_OUT/.gitignore" "$WASM_OUT/package.json" "$WASM_OUT/README.md"

# Optimize WASM binary if wasm-opt is available
WASM_FILE="$WASM_OUT/navi_playground_engine_bg.wasm"
if command -v wasm-opt &>/dev/null; then
    BEFORE=$(stat -f%z "$WASM_FILE" 2>/dev/null || stat -c%s "$WASM_FILE" 2>/dev/null)
    echo "==> Optimizing WASM with wasm-opt (-Oz)..."
    wasm-opt -Oz "$WASM_FILE" -o "$WASM_FILE"
    AFTER=$(stat -f%z "$WASM_FILE" 2>/dev/null || stat -c%s "$WASM_FILE" 2>/dev/null)
    echo "    Before: $BEFORE bytes -> After: $AFTER bytes"
else
    echo "==> wasm-opt not found, skipping optimization."
    echo "    Install binaryen for smaller WASM output."
fi

echo "==> WASM build complete: $WASM_OUT"
ls -lh "$WASM_FILE"
